# Makefile for mine pass

# Path to ttop level of LLVM hierarch
LEVEL = ../../..

LIBRARYNAME = ScottsPass

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym tthe resulting library
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
